name: Test for pipeline

on:
  push:
    branches:
      - content
    paths:
      - ".github/**"

jobs:
  runs-tests-on-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pandas
          pip install openpyxl

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Checkout content branch
        run: |
          git checkout content

      - name: Run test.py script
        run: |
          python .github/script/tests/run_tests.py
